### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by GanerCodes** [nuta/noa#2]
I followed the directions and enabled rustup nightly. I have attached the logs.

`error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "tree_sitter/grammars/markdown/./src" "-o" "/home/ganer/Programs/noa/target/release/build/noa_languages-fbf1746c671c65d2/out/tree_sitter/grammars/markdown/./src/parser.o" "-c" "tree_sitter/grammars/markdown/./src/parser.c" with args "cc" did not execute successfully (status code exit status: 1).`

[log.txt](https://github.com/nuta/noa/files/9157980/log.txt)

**Comment by GanerCodes** [comment]
it appears that the problem is fixed by running `ln -s tree-sitter-markdown/src ./src` inside the markdown folder of the tree_sitter module

**Comment by nuta** [comment]
It appears the repository structure of the [markdown parser](https://github.com/MDeiml/tree-sitter-markdown) has been changed while ago. Thank you for the report! 😄 

Aside that, I'm actively working on writing this editor and `main` will soon be replaced.

**Comment by GanerCodes** [comment]
Thanks. Also to give some extra feedback:
* Need to be able to set keybindings, but I did see this was listed in the todo
* Would like to be able to change how auto parenthesis creation works
* Text cursor is still changed to the vertical line in my terminal after exiting noa

**Comment by nuta** [comment]
They're definitely issues I have to fix. Thanks again 👍
